/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharingRouteImport } from './routes/sharing'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddRouteImport } from './routes/add'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesMealIdRouteImport } from './routes/recipes.$mealId'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as ComparePriceIdRouteImport } from './routes/compare-price.$id'
import { Route as AddManualRouteImport } from './routes/add.manual'

const SharingRoute = SharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesMealIdRoute = RecipesMealIdRouteImport.update({
  id: '/$mealId',
  path: '/$mealId',
  getParentRoute: () => RecipesRoute,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparePriceIdRoute = ComparePriceIdRouteImport.update({
  id: '/compare-price/$id',
  path: '/compare-price/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AddManualRoute = AddManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => AddRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/add': typeof AddRouteWithChildren
  '/auth': typeof AuthRoute
  '/insights': typeof InsightsRoute
  '/notifications': typeof NotificationsRoute
  '/pantry': typeof PantryRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sharing': typeof SharingRoute
  '/add/manual': typeof AddManualRoute
  '/compare-price/$id': typeof ComparePriceIdRoute
  '/item/$id': typeof ItemIdRoute
  '/recipes/$mealId': typeof RecipesMealIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/add': typeof AddRouteWithChildren
  '/auth': typeof AuthRoute
  '/insights': typeof InsightsRoute
  '/notifications': typeof NotificationsRoute
  '/pantry': typeof PantryRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sharing': typeof SharingRoute
  '/add/manual': typeof AddManualRoute
  '/compare-price/$id': typeof ComparePriceIdRoute
  '/item/$id': typeof ItemIdRoute
  '/recipes/$mealId': typeof RecipesMealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/add': typeof AddRouteWithChildren
  '/auth': typeof AuthRoute
  '/insights': typeof InsightsRoute
  '/notifications': typeof NotificationsRoute
  '/pantry': typeof PantryRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sharing': typeof SharingRoute
  '/add/manual': typeof AddManualRoute
  '/compare-price/$id': typeof ComparePriceIdRoute
  '/item/$id': typeof ItemIdRoute
  '/recipes/$mealId': typeof RecipesMealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/add'
    | '/auth'
    | '/insights'
    | '/notifications'
    | '/pantry'
    | '/recipes'
    | '/settings'
    | '/sharing'
    | '/add/manual'
    | '/compare-price/$id'
    | '/item/$id'
    | '/recipes/$mealId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/add'
    | '/auth'
    | '/insights'
    | '/notifications'
    | '/pantry'
    | '/recipes'
    | '/settings'
    | '/sharing'
    | '/add/manual'
    | '/compare-price/$id'
    | '/item/$id'
    | '/recipes/$mealId'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/add'
    | '/auth'
    | '/insights'
    | '/notifications'
    | '/pantry'
    | '/recipes'
    | '/settings'
    | '/sharing'
    | '/add/manual'
    | '/compare-price/$id'
    | '/item/$id'
    | '/recipes/$mealId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AddRoute: typeof AddRouteWithChildren
  AuthRoute: typeof AuthRoute
  InsightsRoute: typeof InsightsRoute
  NotificationsRoute: typeof NotificationsRoute
  PantryRoute: typeof PantryRoute
  RecipesRoute: typeof RecipesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SharingRoute: typeof SharingRoute
  ComparePriceIdRoute: typeof ComparePriceIdRoute
  ItemIdRoute: typeof ItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sharing': {
      id: '/sharing'
      path: '/sharing'
      fullPath: '/sharing'
      preLoaderRoute: typeof SharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$mealId': {
      id: '/recipes/$mealId'
      path: '/$mealId'
      fullPath: '/recipes/$mealId'
      preLoaderRoute: typeof RecipesMealIdRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-price/$id': {
      id: '/compare-price/$id'
      path: '/compare-price/$id'
      fullPath: '/compare-price/$id'
      preLoaderRoute: typeof ComparePriceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add/manual': {
      id: '/add/manual'
      path: '/manual'
      fullPath: '/add/manual'
      preLoaderRoute: typeof AddManualRouteImport
      parentRoute: typeof AddRoute
    }
  }
}

interface AddRouteChildren {
  AddManualRoute: typeof AddManualRoute
}

const AddRouteChildren: AddRouteChildren = {
  AddManualRoute: AddManualRoute,
}

const AddRouteWithChildren = AddRoute._addFileChildren(AddRouteChildren)

interface RecipesRouteChildren {
  RecipesMealIdRoute: typeof RecipesMealIdRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesMealIdRoute: RecipesMealIdRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AddRoute: AddRouteWithChildren,
  AuthRoute: AuthRoute,
  InsightsRoute: InsightsRoute,
  NotificationsRoute: NotificationsRoute,
  PantryRoute: PantryRoute,
  RecipesRoute: RecipesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SharingRoute: SharingRoute,
  ComparePriceIdRoute: ComparePriceIdRoute,
  ItemIdRoute: ItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
